# Generated by Django 3.2 on 2021-08-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallotStyle',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ImageUri', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FileDate', models.CharField(blank=True, max_length=50, null=True)),
                ('IsIncumbent', models.CharField(blank=True, max_length=50, null=True)),
                ('IsTopTicket', models.CharField(blank=True, max_length=50, null=True)),
                ('PostElectionStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('PreElectionStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('SequenceOrder', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateContest',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('HasRotation', models.CharField(blank=True, max_length=1000, null=True)),
                ('Name', models.CharField(blank=True, max_length=2000, null=True)),
                ('SequenceOrder', models.CharField(blank=True, max_length=100, null=True)),
                ('VoteVariation', models.CharField(blank=True, max_length=100, null=True)),
                ('OtherVoteVariation', models.CharField(blank=True, max_length=100, null=True)),
                ('NumberElected', models.CharField(blank=True, max_length=100, null=True)),
                ('VotesAllowed', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSelection',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('SequenceOrder', models.CharField(blank=True, max_length=50, null=True)),
                ('IsWriteIn', models.CharField(blank=True, max_length=50, null=True)),
                ('CandidateIds', models.ManyToManyField(blank=True, max_length=200, to='vip6.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddressLine', models.CharField(blank=True, max_length=1000, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Fax', models.CharField(blank=True, max_length=100, null=True)),
                ('HoursOpenId', models.CharField(blank=True, max_length=100, null=True)),
                ('LatLng', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Uri', models.URLField(blank=True, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('election_administration_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ContactInformation', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ContactInformation')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionAdministration',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AbsenteeUri', models.URLField(blank=True, null=True)),
                ('AmIRegisteredUri', models.URLField(blank=True, null=True)),
                ('BallotTrackingUri', models.URLField(blank=True, null=True)),
                ('BallotProvisionalTrackingUri', models.URLField(blank=True, null=True)),
                ('ElectionsUri', models.URLField(blank=True, max_length=1000, null=True)),
                ('RegistrationUri', models.URLField(blank=True, null=True)),
                ('RulesUri', models.URLField(blank=True, null=True)),
                ('WhatIsOnMyBallotUri', models.URLField(blank=True, null=True)),
                ('WhereDoIVoteUri', models.URLField(blank=True, null=True)),
                ('Department', models.ForeignKey(default='dep1', max_length=2000, on_delete=django.db.models.deletion.CASCADE, to='vip6.department')),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('OtherType', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_error', models.CharField(blank=True, max_length=50, null=True)),
                ('error_object', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FileName', models.CharField(blank=True, max_length=50, null=True)),
                ('Checksum', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalGeospatialFeature',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FileFormat', models.CharField(blank=True, max_length=50, null=True)),
                ('ShapeIdentifier', models.CharField(blank=True, max_length=50, null=True)),
                ('ExternalFileId', models.ForeignKey(db_column='ExternalFileId', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='vip6.externalfile')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('OtherType', models.CharField(blank=True, max_length=100, null=True)),
                ('Value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.CharField(blank=True, max_length=50, null=True)),
                ('EndTime', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoursOpen',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalizedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(default='en', max_length=2)),
                ('LanguageString', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.CharField(max_length=50)),
                ('Longitude', models.CharField(max_length=50)),
                ('Source', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IsMailOnly', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('OtherType', models.CharField(blank=True, max_length=100, null=True)),
                ('ElectionAdministrationId', models.ForeignKey(blank=True, db_column='ElectionAdministrationId', null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.electionadministration')),
                ('ExternalIdentifiers', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=10, null=True)),
                ('IsWriteIn', models.CharField(blank=True, max_length=10, null=True)),
                ('LogoUri', models.URLField(blank=True, null=True)),
                ('ExternalIdentifiers', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier')),
                ('Name', models.ManyToManyField(blank=True, max_length=200, to='vip6.InternationalizedText')),
            ],
        ),
        migrations.CreateModel(
            name='PollingLocation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AddressLine', models.CharField(blank=True, max_length=1000, null=True)),
                ('IsDropBox', models.CharField(blank=True, default='false', max_length=50, null=True)),
                ('IsEarlyVoting', models.CharField(blank=True, default='false', max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('PhotoUri', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IsMailOnly', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Number', models.CharField(blank=True, max_length=50, null=True)),
                ('PrecinctSplitName', models.CharField(blank=True, max_length=50, null=True)),
                ('Ward', models.CharField(blank=True, max_length=50, null=True)),
                ('BallotStyleId', models.ForeignKey(blank=True, db_column='BallotStyleId', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.ballotstyle')),
                ('ElectoralDistrictIds', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ElectoralDistrict')),
                ('ExternalIdentifiers', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier')),
                ('LocalityId', models.ForeignKey(db_column='LocalityId', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='vip6.locality')),
                ('PollingLocationIds', models.ManyToManyField(blank=True, max_length=1000, to='vip6.PollingLocation')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleAddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Line1', models.CharField(max_length=100)),
                ('Line2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Line3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('VipId', models.CharField(blank=True, max_length=50, null=True)),
                ('DateTime', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoterService',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.ForeignKey(blank=True, max_length=2000, on_delete=django.db.models.deletion.CASCADE, to='vip6.internationalizedtext')),
            ],
        ),
        migrations.CreateModel(
            name='StreetSegment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AddressDirection', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('IncludesAllAddresses', models.CharField(blank=True, max_length=50, null=True)),
                ('IncludesAllStreets', models.CharField(blank=True, max_length=50, null=True)),
                ('OddEvenBoth', models.CharField(blank=True, max_length=50, null=True)),
                ('StartHouseNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('EndHouseNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('HouseNumberPrefix', models.CharField(blank=True, max_length=50, null=True)),
                ('HouseNumberSuffix', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('StreetDirection', models.CharField(blank=True, max_length=50, null=True)),
                ('StreetName', models.CharField(blank=True, max_length=50, null=True)),
                ('StreetSuffix', models.CharField(blank=True, max_length=50, null=True)),
                ('UnitNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('Zip', models.CharField(blank=True, max_length=50, null=True)),
                ('PrecinctId', models.ForeignKey(db_column='PrecinctId', on_delete=django.db.models.deletion.CASCADE, to='vip6.precinct')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(default='st1', max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('ElectionAdministrationId', models.ForeignKey(blank=True, db_column='ElectionAdministrationId', null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.electionadministration')),
                ('ExternalIdentifiers', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier')),
                ('PollingLocationIds', models.ManyToManyField(blank=True, max_length=1000, to='vip6.PollingLocation')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExternalGeospatialFeature', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='vip6.externalgeospatialfeature')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsOnlyByAppointment', models.CharField(blank=True, max_length=50, null=True)),
                ('IsOrByAppointment', models.CharField(blank=True, max_length=50, null=True)),
                ('IsSubjectToChange', models.CharField(blank=True, max_length=50, null=True)),
                ('StartDate', models.CharField(blank=True, max_length=50, null=True)),
                ('EndDate', models.CharField(blank=True, max_length=50, null=True)),
                ('Hours', models.ManyToManyField(blank=True, max_length=1000, to='vip6.Hours')),
            ],
        ),
        migrations.AddField(
            model_name='precinct',
            name='SpatialBoundary',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.spatialboundary'),
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='AddressStructured',
            field=models.ManyToManyField(blank=True, null=True, to='vip6.SimpleAddressType'),
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='Directions',
            field=models.ManyToManyField(blank=True, max_length=200, related_name='pl_directions', to='vip6.InternationalizedText'),
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='Hours',
            field=models.ManyToManyField(blank=True, max_length=200, to='vip6.InternationalizedText'),
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='HoursOpenId',
            field=models.ForeignKey(blank=True, db_column='HoursOpenId', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vip6.hoursopen'),
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='LatLng',
            field=models.ManyToManyField(blank=True, db_column='LatLng', max_length=50, null=True, to='vip6.LatLng'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('Nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('Prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('Suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('ContactInformation', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ContactInformation')),
                ('ExternalIdentifiers', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier')),
                ('FullName', models.ManyToManyField(blank=True, max_length=200, related_name='person_full_name', to='vip6.InternationalizedText')),
                ('PartyId', models.ForeignKey(blank=True, db_column='PartyId', null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.party')),
                ('Profession', models.ManyToManyField(blank=True, max_length=200, related_name='person_profession', to='vip6.InternationalizedText')),
                ('Title', models.ManyToManyField(blank=True, max_length=200, related_name='person_title', to='vip6.InternationalizedText')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedContest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ContestId', models.ForeignKey(blank=True, db_column='ContestId', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.candidatecontest')),
                ('OrderedBallotSelectionIds', models.ManyToManyField(blank=True, max_length=1000, to='vip6.CandidateSelection')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FilingDeadline', models.CharField(blank=True, max_length=100, null=True)),
                ('IsPartisan', models.CharField(blank=True, max_length=100, null=True)),
                ('Term', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactInformation', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ContactInformation')),
                ('Description', models.ManyToManyField(blank=True, max_length=200, related_name='office_description', to='vip6.InternationalizedText')),
                ('ElectoralDistrictId', models.ForeignKey(blank=True, db_column='ElectoralDistrictId', null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.electoraldistrict')),
                ('ExternalIdentifiers', models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier')),
                ('Name', models.ManyToManyField(blank=True, max_length=200, related_name='office_name', to='vip6.InternationalizedText')),
                ('OfficeHolderPersonIds', models.ManyToManyField(blank=True, to='vip6.Person')),
            ],
        ),
        migrations.AddField(
            model_name='locality',
            name='PollingLocationIds',
            field=models.ManyToManyField(blank=True, max_length=10000, to='vip6.PollingLocation'),
        ),
        migrations.AddField(
            model_name='locality',
            name='StateId',
            field=models.ForeignKey(blank=True, db_column='StateId', null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.state'),
        ),
        migrations.AddField(
            model_name='hoursopen',
            name='Schedule',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.Schedule'),
        ),
        migrations.AddField(
            model_name='electoraldistrict',
            name='ExternalIdentifiers',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier'),
        ),
        migrations.CreateModel(
            name='ElectionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeUri', models.URLField(blank=True, null=True)),
                ('NoticeText', models.ManyToManyField(blank=True, max_length=5000, to='vip6.InternationalizedText')),
            ],
        ),
        migrations.AddField(
            model_name='electionadministration',
            name='ElectionNotice',
            field=models.ManyToManyField(blank=True, null=True, to='vip6.ElectionNotice'),
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('HoursOpenId', models.CharField(blank=True, max_length=50, null=True)),
                ('IsStatewide', models.CharField(blank=True, max_length=10, null=True)),
                ('ResultsUri', models.URLField(blank=True, null=True)),
                ('HasElectionDayRegistration', models.CharField(blank=True, max_length=10, null=True)),
                ('RegistrationDeadline', models.CharField(blank=True, max_length=50, null=True)),
                ('AbsenteeRequestDeadline', models.CharField(blank=True, max_length=50, null=True)),
                ('AbsenteeBallotInfo', models.ManyToManyField(blank=True, max_length=200, related_name='absentee_ballot_info', to='vip6.InternationalizedText')),
                ('ElectionType', models.ManyToManyField(blank=True, max_length=200, related_name='election_type', to='vip6.InternationalizedText')),
                ('Name', models.ManyToManyField(blank=True, max_length=200, related_name='election_name', to='vip6.InternationalizedText')),
                ('PollingHours', models.ManyToManyField(blank=True, max_length=200, related_name='election_hours', to='vip6.InternationalizedText')),
                ('RegistrationInfo', models.ManyToManyField(blank=True, max_length=200, related_name='election_registration_info', to='vip6.InternationalizedText')),
                ('StateId', models.ForeignKey(db_column='StateId', on_delete=django.db.models.deletion.CASCADE, to='vip6.state')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='ElectionOfficialPersonId',
            field=models.ForeignKey(blank=True, db_column='ElectionOfficialPersonId', null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.person'),
        ),
        migrations.AddField(
            model_name='department',
            name='VoterService',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.voterservice'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='Directions',
            field=models.ManyToManyField(blank=True, max_length=200, to='vip6.InternationalizedText'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='EndorsementPartyIds',
            field=models.ManyToManyField(blank=True, max_length=200, to='vip6.Party'),
        ),
        migrations.AddField(
            model_name='candidatecontest',
            name='BallotSelectionIds',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.CandidateSelection'),
        ),
        migrations.AddField(
            model_name='candidatecontest',
            name='BallotSubTitle',
            field=models.ManyToManyField(blank=True, max_length=200, related_name='cc_ballot_sub_title', to='vip6.InternationalizedText'),
        ),
        migrations.AddField(
            model_name='candidatecontest',
            name='BallotTitle',
            field=models.ManyToManyField(blank=True, max_length=200, related_name='cc_ballot_title', to='vip6.InternationalizedText'),
        ),
        migrations.AddField(
            model_name='candidatecontest',
            name='ElectoralDistrictId',
            field=models.ForeignKey(db_column='ElectoralDistrictId', max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='vip6.electoraldistrict'),
        ),
        migrations.AddField(
            model_name='candidatecontest',
            name='ElectorateSpecification',
            field=models.ManyToManyField(blank=True, max_length=200, related_name='cc_electorate_specification', to='vip6.InternationalizedText'),
        ),
        migrations.AddField(
            model_name='candidatecontest',
            name='ExternalIdentifiers',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier'),
        ),
        migrations.AddField(
            model_name='candidatecontest',
            name='OfficeIds',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.Office'),
        ),
        migrations.AddField(
            model_name='candidatecontest',
            name='PrimaryPartyIds',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.Party'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='BallotName',
            field=models.ManyToManyField(blank=True, max_length=200, to='vip6.InternationalizedText'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ContactInformation',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.ContactInformation'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ExternalIdentifiers',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.ExternalIdentifier'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='PartyId',
            field=models.ForeignKey(blank=True, db_column='PartyId', null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.party'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='PersonId',
            field=models.ForeignKey(blank=True, db_column='PersonId', null=True, on_delete=django.db.models.deletion.CASCADE, to='vip6.person'),
        ),
        migrations.AddField(
            model_name='ballotstyle',
            name='OrderedContestIds',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.OrderedContest'),
        ),
        migrations.AddField(
            model_name='ballotstyle',
            name='PartyIds',
            field=models.ManyToManyField(blank=True, max_length=1000, to='vip6.Party'),
        ),
        migrations.CreateModel(
            name='BallotMeasureSelection',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('SequenceOrder', models.CharField(blank=True, max_length=50, null=True)),
                ('Selection', models.ManyToManyField(blank=True, max_length=200, to='vip6.InternationalizedText')),
            ],
        ),
        migrations.CreateModel(
            name='BallotMeasureContest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('HasRotation', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('SequenceOrder', models.CharField(blank=True, max_length=100, null=True)),
                ('VoteVariation', models.CharField(blank=True, max_length=100, null=True)),
                ('OtherVoteVariation', models.CharField(blank=True, max_length=100, null=True)),
                ('InfoUri', models.URLField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('OtherType', models.CharField(blank=True, max_length=50, null=True)),
                ('BallotSelectionIds', models.ManyToManyField(blank=True, max_length=1000, to='vip6.BallotMeasureSelection')),
                ('BallotSubTitle', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_ballot_sub_title', to='vip6.InternationalizedText')),
                ('BallotTitle', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_ballot_title', to='vip6.InternationalizedText')),
                ('ConStatement', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_con_statement', to='vip6.InternationalizedText')),
                ('EffectOfAbstain', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_effect_of_abstain', to='vip6.InternationalizedText')),
                ('ElectoralDistrictId', models.ForeignKey(blank=True, db_column='ElectoralDistrictId', on_delete=django.db.models.deletion.CASCADE, to='vip6.electoraldistrict')),
                ('ElectorateSpecification', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_electorate_specification', to='vip6.InternationalizedText')),
                ('ExternalIdentifiers', models.ManyToManyField(blank=True, max_length=200, to='vip6.ExternalIdentifier')),
                ('FullText', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_full_text', to='vip6.InternationalizedText')),
                ('PassageThreshold', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_passage_threshold', to='vip6.InternationalizedText')),
                ('ProStatement', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_pro_statement', to='vip6.InternationalizedText')),
                ('SummaryText', models.ManyToManyField(blank=True, max_length=200, related_name='bmc_summary_text', to='vip6.InternationalizedText')),
            ],
        ),
    ]
